### ISSUE TITLE
Matrix blocks are invisible while viewing revisions

### ISSUE THREAD

**Issue by Mosnar** [vaersaagod/matrixmate#11]
While viewing revisions, there is some CSS applied that makes the matrix blocks invisible.
![image](https://user-images.githubusercontent.com/3810939/65718394-6f9d0b00-e071-11e9-90f7-a65381a675cd.png)

Craft 3.3.5
MatrixMate 1.2.1

**Comment by mmikkel** [comment]
Thanks for reporting, @Mosnar – I'll try to get a fix out shortly.

**Comment by mmikkel** [comment]
Hi @Mosnar – this issue should be resolved in [MatrixMate 1.2.2](https://github.com/vaersaagod/matrixmate/releases/tag/v1.2.2).
