### ISSUE TITLE
Double borders with Craft 3.4.7

### ISSUE THREAD

**Issue by jamiewade** [vaersaagod/matrixmate#18]
Craft 3.4.7 is now out which has introduced some improvements to the matrix block UI: https://github.com/craftcms/cms/issues/5652#issuecomment-589081201

However this has now introduced a double borders issue with the plugin:

![Screenshot_2020-02-21 Sitemap - Arebray](https://user-images.githubusercontent.com/6672331/75034009-2330ec80-54a4-11ea-906f-763a4a2db32a.png)

**Comment by mmikkel** [comment]
Thanks for reporting @jamiewade.

**Comment by mmikkel** [comment]
I just published [MatrixMate 1.2.5](https://github.com/vaersaagod/matrixmate/releases/tag/v1.2.5), which fixes this issue.
