### ISSUE TITLE
Redactor link functionality

### ISSUE THREAD

**Issue by jan-thoma** [vaersaagod/matrixmate#19]
When using maxtrixmate in combination with redactor. The add Files and Link popup is located under the popup. see screenshot.
![Bildschirmfoto 2020-03-17 um 15 41 45](https://user-images.githubusercontent.com/24450307/76867473-dacbdb00-6865-11ea-92ae-8829f33e0a02.png)

**Comment by mmikkel** [comment]
I'm only able to reproduce this when editing an entry in an element editor modal, and it happens regardless of whether MatrixMate is installed/enabled or not. 

Probably a bug in Craft or the Redactor plugin?

(I tested on Craft 3.4.9 & Redactor 2.6.0.1)

**Comment by mmikkel** [comment]
I can confirm that this is a bug in Craft or the Redactor plugin. I created an [issue over at the Craft repo](https://github.com/craftcms/cms/issues/5805).

**Comment by mmikkel** [comment]
[Redactor 2.6.1 is out now, which resolves this issue.](https://github.com/craftcms/redactor/issues/215)
