### ISSUE TITLE
Required

### ISSUE THREAD

**Issue by samuelbirch** [vaersaagod/matrixmate#2]
It would also be great if we could override the required field status from within the config on a per field in a tab basis

**Comment by mmikkel** [comment]
Hi @samuelbirch – again, sorry for the very late reply.

Back when I built [Reasons](https://github.com/mmikkel/Reasons-Craft) for Craft 2, I went down the rabbit hole in trying to override the `required` status for specific fields. It was basically impossible to do then, and I don't think this has changed much in Craft 3 (basically, required fields are evaluated when Craft validates elements before saving them – which happens deep down in the ElementsService core and isn't something that can really be overridden without actually changing the `required` property for that field in the database).

So, I don't think this is something we will be able to do, although I'll leave this FR open for the time being.
