### ISSUE TITLE
Specify display order of ungrouped blocks

### ISSUE THREAD

**Issue by chasegiunta** [vaersaagod/matrixmate#20]
First of all, huge thank you for filling the functionality gaps with this plugin!

Apologies if this is somehow already possible and I missed it, but I believe currently, if you're not specifying a group for a block type to reside in, it will always show up _first_ in the order of groups.

![image](https://user-images.githubusercontent.com/1377169/80493183-b0704180-892a-11ea-8860-ce70f874d2af.png)

It would be great if we could configure these _orphans_ to show up _last_, rather than _first_, in the list of group buttons.

**Comment by mmikkel** [comment]
Hi @chasegiunta, thanks for the input!

I agree, that'd be a nice little feature/setting. I'll look into adding that sometime soon.

**Comment by mmikkel** [comment]
Took me long enough, but I just added a new [`ungroupedTypesPosition`](https://github.com/vaersaagod/matrixmate#ungroupedtypesposition-string) field config setting that should resolve this 🎉 

Added to both the Craft 3 and Craft 4 compatible plugins (`1.5.0` and `2.1.0`, respectively).
