### ISSUE TITLE
[FR] Add support for a field level maxLimit

### ISSUE THREAD

**Issue by rungta** [vaersaagod/matrixmate#21]
It would be great to have support for controlling the maximum number of blocks permitted for a Matrix field regardless of block type. Craft lets us configure this number while creating a matrix field but sometimes different limits are appropriate for different contexts.

**Comment by rungta** [comment]
@mmikkel Any chance of upvoting this feature request? 😬

A use case we run into often — we have a matrix field for capturing links with two block types. One with an entry field for internal links and one with a URL field for external links. We use this field in various contexts, and in most contexts the thing we want to restrict is the maximum number of blocks (regardless of type). For example, in a header global set it might be five; in the footer it might be two, in a banner context it might be one.

**Comment by mmikkel** [comment]
Hi @rungta, upvote registered :)

**Comment by pl-mnm** [comment]
This feature request gets my vote as well!
