### ISSUE TITLE
Solspace Calendar Support

### ISSUE THREAD

**Issue by onebrightlight** [vaersaagod/matrixmate#22]
Currently MatrixMate only supports contexts for Entries, Categories, Global Sets and User groups.

It’d be great if it could support @Solspace’s Calendar Event elements as well. Currently I am restricted from adding our standard content builder to its pages as there is no way to customize the available blocks and tabs to it. I can leverage some CSS and JS to hide them myself, but obviously this is less than ideal as the buttons and features will remain there.

**Comment by mmikkel** [comment]
Hi @onebrightlight – I can probably add support for Calendar Events as a context, but I don't know exactly when I get around to it (I'd also accept a PR that added support, if you're up for it). 

In the meantime, if you really need this ASAP, you can actually hack it in yourself.

The nice thing about having a PHP-based config is that it's... PHP. So there's nothing stopping you from using some PHP to determine if the current request is rendering a Calendar Event inside the CP, and return a different MatrixMate config altogether if that is the case. Something like this should do it (this would be your `config/matrixmate.php` file):

```php
<?php

// Check if this is a CP request. If not, then just return an empty array (note: replace 'admin' with whatever your cpTrigger actually is
$isCpRequest = \explode('/', \parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH))[1] ?? null === 'admin';
if (!$isCpRequest) {
    return [];
}

// Look at the URL segments to determine if this is a Solspace Calendar Event
$segments = Craft::$app->getRequest()->getSegments();
$isSolspaceCalendar = \count($segments) >= 3 && $segments[0] === 'calendar' && $segments[1] === 'events' && !!((int)$segments[2]);

if ($isSolspaceCalendar) {
    // Return whatever config you need for Solspace Calendar Events. Note that we don't use a context at all here
    return [
        'fields' => [
            'anAwesomeMatrixField' => [
                'groups' => [[
                    ...
                ]],
            ],
        ],
    ];
}

// This isn't Solspace Calendar Events; return the normal/global config
return [
    'fields' => [
        ...
    ],
];
```

**Comment by mmikkel** [comment]
Decided not to support any third party plugins, due to desire to retain my sanity.
