### ISSUE TITLE
Cannot install on 3.4.22.1, unable to determine the base path

### ISSUE THREAD

**Issue by masiorama** [vaersaagod/matrixmate#23]
Hello, I just tried to install the plugin on the latest Craft CMS version 3.4.22.1, but it is not working.
This is the message:
`
[craft\composer\InvalidPluginException]
  Couldn't install vaersaagod/matrixmate: Unable to determine the base path
`

What am I doing wrong? Any suggestions?
Thanks in advance.

**Comment by mmikkel** [comment]
Haven't seen that error before, and I'm not able to reproduce this (just tested installing MatrixMate on a fresh 3.4.22.1 install, both using Composer and via the Control Panel). 

Are you able to install other plugins?

**Comment by masiorama** [comment]
Yes, I just tried to install another plugin via the CP and it worked wihout issues.
Tried again via CP with MatrixMate and the complete log is this:

> Errore: Couldn't install vaersaagod/matrixmate: Unable to determine the base path
> 
> Risultato Composer: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
> Package "danielstjules/stringy" listed for update is not installed. Ignoring.
> Loading composer repositories with package information
> Updating dependencies
> Package operations: 1 install, 0 updates, 0 removals
> - Installing vaersaagod/matrixmate (1.2.5): Loading from cache
> Failed to execute unzip -qq '/shared/httpd/masiorama2/vendor/vaersaagod/matrixmate/dce2ca048a5e71d14c955a572ada56fa' -d '/shared/httpd/masiorama2/vendor/composer/9c514584'
> 
> [/shared/httpd/masiorama2/vendor/vaersaagod/matrixmate/dce2ca048a5e71d14c955a572ada56fa]
> End-of-central-directory signature not found. Either this file is not
> a zipfile, or it constitutes one disk of a multi-part archive. In the
> latter case the central directory and zipfile comment will be found on
> the last disk(s) of this archive.
> note: /shared/httpd/masiorama2/vendor/vaersaagod/matrixmate/dce2ca048a5e71d14c955a572ada56fa may be a plain executable, not an archive
> unzip: cannot find zipfile directory in one of /shared/httpd/masiorama2/vendor/vaersaagod/matrixmate/dce2ca048a5e71d14c955a572ada56fa or
> /shared/httpd/masiorama2/vendor/vaersaagod/matrixmate/dce2ca048a5e71d14c955a572ada56fa.zip, and cannot find /shared/httpd/masiorama2/vendor/vaersaagod/matrixmate/dce2ca048a5e71d14c955a572ada56fa.ZIP, period.
> 
> The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
> Unzip with unzip command failed, falling back to ZipArchive class
> - Removing vaersaagod/matrixmate (1.2.5)

**Comment by masiorama** [comment]
Ok I just notices it could be a cache problem. I'll be back in a minute.

**Comment by mmikkel** [comment]
That's odd. I considered a possible capitalization issue, but I don't think there are any in the plugin source files.

Can you try `composer clear-cache && composer require vaersaagod/matrixmate` and see if that works? If not, I think this might be an issue for the Craft repo.

**Comment by mmikkel** [comment]
Also, which environment are you on? Mac/Windows/VM?

**Comment by masiorama** [comment]
Ok it was a cache problem indeed. It happened because the first time I tried to install my laptop crashed (I'm struggling with it for weeks) in the middle of the operation, therefore broken cached package.
Tried with `composer clearcache` and then installed the plugin via CP and it worked like a charm.
Thanks for all!

**Comment by mmikkel** [comment]
Awesome, thanks for following up :)
