### ISSUE TITLE
Translate in a different language

### ISSUE THREAD

**Issue by masiorama** [vaersaagod/matrixmate#24]
Hello, I encounter an error log message due to the fact that the plugin translation is available only in english (aka /src/translations/en/matrixmate.php). The message I get is 
`The message file for category 'matrixmate' does not exist: /shared/httpd/masiorama2/vendor/vaersaagod/matrixmate/src/translations/it-IT/matrixmate.php Fallback file does not exist as well: /shared/httpd/masiorama2/vendor/vaersaagod/matrixmate/src/translations/it/matrixmate.php`

If I copy the matrixmate.php file into /translations/it the problem is gone.
I don't know if this is the right way to solve it, but just in case I could make a pull request with the file.
Otherwise, what is the right way to solve it?
I know it is just a log message, but I like to have my console bar clean :).
Thanks!

**Comment by mmikkel** [comment]
Hi @masiorama – sorry for the late reply.

Copying the `matrixmate.php` translations file to your site's `translations/it` folder is the right way to solve it :)

Like you say, it's just a log message and not really an error, and we can't/won't bundle a translation file for every locale supported by Yii.
