### ISSUE TITLE
Compatibility with Craft 3.5

### ISSUE THREAD

**Issue by adrienpicard** [vaersaagod/matrixmate#26]
**Description**
The new field layout in 3.5 introduces a bug where Tabs are not created in Matrix Blocks.

**Steps to reproduce**

1. Upgrade to Craft ^3.5.0-RC1
2. Define one or more tabs in matrixmate.php for one Matrix fields

**Additional info**
Fields structure has changed and are now wrapped in a `.flex-fields` element.

**Comment by mmikkel** [comment]
Thanks for reporting that @adrienpicard. I'll get a fix out shortly.

**Comment by mmikkel** [comment]
Should be resolved in [MatrixMate v1.2.6](https://github.com/vaersaagod/matrixmate/releases/tag/v1.2.6)

**Comment by adrienpicard** [comment]
Thanks for the quick fix @mmikkel
