### ISSUE TITLE
Not working with Craft 3.5 custom field widths

### ISSUE THREAD

**Issue by TheFunkyMonk** [vaersaagod/matrixmate#27]
## Description

When MatrixMate is handling the grouping of a matrix field into tabs, the new "Custom Field Widths" feature in Craft 3.5 (under "Author Experience" in the [release post](https://craftcms.com/blog/craft-3-5-released)) does not work.

I totally realize this is a brand new feature and could take some time to support, just thought I'd give you a heads up.

## Steps to Reproduce

1. Set up a Matrix field with several fields.
2. Use the Custom Field Widths feature of the new field layout designer to set two fields side-by-side.
3. Configure MatrixMate to group the fields into one or more tabs.

### Expected Result
Fields maintain their side-by-side display within their set tab.

### Actual Result
Fields display full-width and stacked as in previous versions of Craft.

## Additional Info

Craft version: 3.5.3
PHP version: 7.3.8
Database driver & version: MySQL v5.7.26

Here's another post that hopefully is helpful: [Upgrading to Craft 3.5 - New Field Layout Features](https://craftcms.com/knowledge-base/upgrading-to-craft-3-5#new-field-layout-features)

**Comment by mmikkel** [comment]
Thanks for reporting @TheFunkyMonk – should be resolved in [MatrixMate v1.2.7](https://github.com/vaersaagod/matrixmate/releases/tag/v1.2.7)
