### ISSUE TITLE
[Question/Feature Request] Support for matrix nested in super table

### ISSUE THREAD

**Issue by davist11** [vaersaagod/matrixmate#28]
Is there a plan/timeline for supporting matrix fields nested inside super table?

**Comment by mmikkel** [comment]
Hi @davist11 👋 

Sorry, we have no plans to implement support for nested Matrix fields. I believe the Spoon plugin does it, though.

**Comment by davist11** [comment]
Got it, thanks! Hah we just like MatrixMate so much more...
