### ISSUE TITLE
Global configuration is not applied to other sections

### ISSUE THREAD

**Issue by dgsiegel** [vaersaagod/matrixmate#29]
Suppose you have a configuration file like this one:

```
<?php

return [
  'fields' => [
    'fieldHandle' => [
      '*' => [
        'groups' => [
          [
            'label' => 'Titles',
            'types' => ['hero'],
          ],
          [
            'label' => 'Content',
            'types' => ['quote', 'text']
          ],
        ],
      ],
      'entryType:contentType' => [
        'hiddenTypes' => ['quote'],
      ],
    ],
  ],
];
```

I would expect that groups applied for `*` would also apply for all groups below, e.g. `entryType:contentType`. But `entryType:contentType` starts with an empty configuration and I would have to duplicate `groups`.

**Comment by mmikkel** [comment]
That behaviour is by design. I think that recursively merging the global context into the context specific ones would quickly become unwieldy for anything except the simplest configs – which is why we chose to do it like that and not mimic how Craft's multi-environment configs work.

You can always accomplish what you need using some PHP, though. Something like this should work:

```php
<?php

$someMatrixFieldConfig = [
    'groups' => [
          [
            'label' => 'Titles',
            'types' => ['hero'],
          ],
          [
            'label' => 'Content',
            'types' => ['quote', 'text']
          ],
];

return [
    'fields' => [
        'fieldHandle' => [
            '*' => $someMatrixFieldConfig,
            'entryType:contentType' => \array_merge_recursive($someMatrixFieldConfig, [
                'hiddenTypes' => ['quote'],
            ]),
        ],
    ],
];
```

**Comment by dgsiegel** [comment]
Works great, thanks! Might be a great addition to the Readme, as I assumed it would work like Craft's multi-environment configs.

**Comment by mmikkel** [comment]
@dgsiegel Sure, a bit of clarification in the docs couldn't hurt. I'll look into adding that!
