### ISSUE TITLE
CSS glitch when close to browser bottom edge

### ISSUE THREAD

**Issue by naboo** [vaersaagod/matrixmate#3]
When you are close to the browser bottom edge, and you have one group with only one type in it there's a small CSS glitch. If you have two types in the group the popup goes up, instead of down.

![Untitled-1](https://user-images.githubusercontent.com/1220045/57459164-f98b3980-7272-11e9-9b34-99bc07eec943.png)

**Comment by mmikkel** [comment]
@naboo Thanks for reporting! That looks like it could do with a bit of polish, for sure. 

Which browser are you using in the above screenshot?

**Comment by naboo** [comment]
Latest Firefox :)

Den tors 9 maj 2019 19:21M. Mikkel Rummelhoff <notifications@github.com>
skrev:

**Comment by mmikkel** [comment]
Should be resolved in [v1.1.3](https://github.com/vaersaagod/matrixmate/releases/tag/v1.1.3)!
