### ISSUE TITLE
MatrixMate initialises for Matrix fields inside SuperTable fields

### ISSUE THREAD

**Issue by mmikkel** [vaersaagod/matrixmate#31]
As reported by #30, it appears that MatrixMate initialises for Matrix fields nested in SuperTable fields. It's not supposed to do that.

**Comment by japo32** [comment]
I can verify that this is indeed a bug.

![Screen Shot 2021-06-11 at 1 17 53 PM](https://user-images.githubusercontent.com/676680/121616731-94404d00-cab7-11eb-8047-b8bf4261f152.png)

**Comment by mmikkel** [comment]
Unable to reproduce this at all. If this was/is in fact an issue with MatrixMate, it might've been fixed in a previous release. Alternatively, the problem is due to some other JS error on the page.

If somebody is able to verify that this is still occurring, it'd be great if they could get in touch.
