### ISSUE TITLE
Add ability to add icons to block labels

### ISSUE THREAD

**Issue by daltonrooney** [vaersaagod/matrixmate#33]
I was wondering how hard it would be to support icons in the matrix dropdown?

![Screen Shot 2021-06-01 at 1 10 20 PM](https://user-images.githubusercontent.com/742045/120384296-d2c95100-c2da-11eb-9f6f-9a513e768e25.png)

I was just testing out [Vizy](https://verbb.io/craft-plugins/vizy/features) and the visual block chooser is very nice:

![Screen Shot 2021-06-01 at 1 12 23 PM](https://user-images.githubusercontent.com/742045/120384468-115f0b80-c2db-11eb-9d23-304090ed6945.png)

I believe this is something we could do in CSS but support in the config file would be even nicer. 😀

**Comment by mmikkel** [comment]
Interesting idea, thanks. I'll give it a think.

**Comment by mmikkel** [comment]
Gave it a good think and decided not to implement something like this. Thanks for the suggestion, though (would probably accept a PR).
