### ISSUE TITLE
Change of Entry Types leave the fields saved

### ISSUE THREAD

**Issue by reachpriti12** [vaersaagod/matrixmate#35]
Hi, I need help with Matrix Mate plugin. Currently, we have two different types of entry type. Entry type 1 has image gallery and entry type two doesn’t have image gallery that how we have set the matrixmate. 

What is happening is when I switch from entry1 to entry 2 I can still see the image gallery in entry 2. Shouldn’t it be switch to entry2 fields assigned.

**Comment by mmikkel** [comment]
Hi @reachpriti12, can you share your `config/matrixmate.php` file?

**Comment by reachpriti12** [comment]
```
<?php

return [
	'fields' => [
		'contentBlocks' => [
			'*' => [
				'groups' => [
					[
						'label' => 'Text',
						'types' => ['heading', 'richText', 'blockquote', 'accordion', 'table'],
					],
					[
						'label' => 'Media',
						'types' => ['imageGallery', 'fullwidthImage', 'video'],
					],
					[
						'label' => 'Related Content',
						'types' => ['links', 'callToAction', 'relatedArticles', 'relatedPeople'],
					],
					[
						'label' => 'Misc.',
						'types' => ['form', 'tableOfContents'],
					],
				],
				'hideUngroupedTypes' => true,
			],
			'entryType:childListing,entryType:newsListing' => [
				'groups' => [
					[
						'label' => 'Text',
						'types' => ['heading', 'richText', 'blockquote', 'accordion'],
					],
					[
						'label' => 'Media',
						'types' => ['downloads', 'links'],
					],
				],
				'hideUngroupedTypes' => true,
			],
		]
	],
];

```

**Comment by reachpriti12** [comment]
Here what is happening is when I turn my content entry type to childListing or newsListing. If the admin user has earlier added image gallery or any other content in the content entry type after switching to childListing it will still display there.

**Comment by mmikkel** [comment]
That's expected. MatrixMate won't hide existing blocks, only block type buttons – meaning the the "Image Gallery" button shouldn't be visible for your `childListing` or `newsListing` entry types, but any existing Image Gallery blocks will still be visible (both in the control panel and on the frontend of your site, unless you filter them out in Twig).

**Comment by reachpriti12** [comment]
Is there any best way to work around this as client keeps making mistake around this,

**Comment by mmikkel** [comment]
Not really that I can think of. You could check out the [Spoon plugin](https://plugins.craftcms.com/spoon), maybe it has a solution for this.

The fact that MatrixMate doesn't hide blocks is a deliberate design choice on our end. If the blocks were simply hidden (i.e. with CSS) in the control panel, users would inevitably run into the awkward situation were blocks that are hidden in the control panel, would still show up on the front end. The only solution to that would be if MatrixMate actually deleted (or disabled) hidden blocks when the entry or draft is saved, but that would run counter to the plugin's philosophy of never actually touching your content.
