### ISSUE TITLE
FR: UI elements and field layout

### ISSUE THREAD

**Issue by TomDeSmet** [vaersaagod/matrixmate#37]
It would be super nice if we could add UI elements such as headers and horizontal lines just like we can in the Craft field layout.
Also defining the width of a field so we can put multiple light switches next to each other would be superb.

So in short, recreate the field layout from Craft in MatrixMate :)

I the config I think headers and horizontal lines could be added between fields by using for example:

```
[
    'label' => 'Categorie filters',
    'fields' => [
        'filterCategories',
        'filterBrands',
        '<h2[Title]>',
        'filterThemes',
        'filterChannels',
        '<hr>',
        'filterMaterial'
    ]
]
```

Added the `<` and `>` because field handles could be HR or H2 also.
For the field widths we could maybe create an array to address a field instead of the String handle?

```
[
    'handle' => 'filterBakingType',
    'col' => 2
]
```

Not so sure how feasible it is to actually develop it.

**Comment by mmikkel** [comment]
Hi @TomDeSmet, thanks for the suggestion(s)!

> It would be super nice if we could add UI elements such as headers and horizontal lines just like we can in the Craft field layout.

Have you seen the [UI Elements Field](https://plugins.craftcms.com/ui-element-fields) plugin? It lets you create Matrix sub-fields that render native Craft UI elements. Seems like a decent solution for the time being.

> Also defining the width of a field so we can put multiple light switches next to each other would be superb

Configuring Matrix sub fields' width is supported in Craft core, not sure why we should add the same capability to MatrixMate?

**Comment by TomDeSmet** [comment]
My God, so sorry, I forgot about both of these.
Pretend this post never happened :)
