### ISSUE TITLE
CSS issue with collapsed blocks

### ISSUE THREAD

**Issue by naboo** [vaersaagod/matrixmate#4]
When I use collapsed blocks the layout gets messed up. See attached. Works perfectly fine not collapsed.

![Screenshot_2019-05-09 🚧⚙ Blocks - KÖPA](https://user-images.githubusercontent.com/1220045/57459659-ef1d6f80-7273-11e9-981a-e3a33f3112ed.png)

**Comment by mmikkel** [comment]
Ouch, thanks for reporting @naboo – I'll get that sorted ASAP.

**Comment by mmikkel** [comment]
Should be resolved in [v1.1.3](https://github.com/vaersaagod/matrixmate/releases/tag/v1.1.3)!
