### ISSUE TITLE
Ability to disable a specific type on a specific section but preserve default groups and types from global config

### ISSUE THREAD

**Issue by Antimated** [vaersaagod/matrixmate#40]
Hi!

Is there any way that I can disable 1 type on a specific section without losing all my groups and types? I tried using the `*`global config to set my defaults and to overwrite 1 type like so:

![Screenshot 2022-01-21 at 10 50 41](https://user-images.githubusercontent.com/2869409/150505589-82f1a099-4f46-4707-ad5d-244a5ceeccf1.png)

but it seems that I have to set my groups and types manually for each config type. Could something like this be possible?

![759c7f38-fd6a-482f-9455-bb2fb8c7b8d1](https://user-images.githubusercontent.com/2869409/150507291-cbc263b5-9072-4be0-a2a8-05d83353f41a.jpeg)

**Comment by mmikkel** [comment]
Hi @Antimated – the current behaviour is by design; look [here](https://github.com/vaersaagod/matrixmate/issues/29) for more details and a workaround.
