### ISSUE TITLE
Control Over Default Tab Order

### ISSUE THREAD

**Issue by itsmattsoria** [vaersaagod/matrixmate#41]
I would definitely call this an enhancement, but here's the scenario:

I want all fields except for one to be displayed in the initial tab of a matrix field, and then I want this one field (a purely instructional field using [UI Elements Fields](https://plugins.craftcms.com/ui-element-fields)) to be displayed in its own tab. It'd be great to only have to specify this special case tab in the Matrix Mate config and then let Matrix Mate's default behavior of handling unspecified fields into a default tab called "Fields" handle the rest, but as far as I can tell, when you define a tab, that tab is treated as the initial/active tab, and then the default "Fields" tabs comes second. In my case I want the opposite to happen. I know I can just create another custom tab and list the rest of the fields, but it'd be great if you could do something like this:

```
'types' => [
  'myField' => [
    'tabs' => [[
      'label' => 'Content',
      'fields' => ['*'],
    ], [
      'label' => 'Instructions',
      'fields' => ['instructionalField'],
    ]],
  ],
],
```

Maybe that `'*'` would be doing too much lifting to say "all unassigned fields"? Maybe you'd have to be a little more specific, like `'!== instructionalField'` or something like that, not sure. Or maybe this is beating around the bush too much and you just assign the tab and let the default tab catch all unassigned fields as is already the case but there's just another `order` option to add to `tabs` that could be like `['Fields', 'Instructions']`?

**Comment by mmikkel** [comment]
Hi @itsmattsoria – unless I misunderstand you, it sounds like the [`defaultTabFirst`](https://github.com/vaersaagod/matrixmate#defaulttabfirst-bool) setting already covers the use case? And, you can use the [`defaultTabName`](https://github.com/vaersaagod/matrixmate#defaulttabname-stringbool) setting to give the default tab a different name (e.g. "Content", instead of "Fields"). 

Something like this should cover the example given here:  

```php
'types' => [
  'myField' => [
    'tabs' => [[
      'label' => 'Instructions',
      'fields' => ['instructionalField'],
    ]],
    'defaultTabName' => 'Content',
    'defaultTabFirst' => true,
  ],
],
```

**Comment by itsmattsoria** [comment]
@mmikkel wow, how did I not see that option in the documentation? It's there! Thank you — disregard!
