### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by Antimated** [vaersaagod/matrixmate#43]
Any plans to support Craft CMS 4? I'm just wondering because I'm checking every plugin that our company uses on a regular basis :)

EDIT: can't currently install it via the plugin store, didn't try installing it via CLI though.

**Comment by mmikkel** [comment]
Yeah, I expect we'll get a version out in time for the GA release.

**Comment by mmikkel** [comment]
Just tagged v. 2.0.0-beta.1, which is compatible with the latest Craft 4.0 beta release. This is a major refactor of the plugin, hence the beta – we'll have a stable release out around the 4.0 GA release.

**Comment by mmikkel** [comment]
Just tagged v. 2.0.0.
