### ISSUE TITLE
MatrixMate CSS loading in Commerce email previews

### ISSUE THREAD

**Issue by pixelmachine** [vaersaagod/matrixmate#44]
MatrixMate's CSS is loading on Commerce email previews and causing layout issues. Specifically:
A URL like this `/index.php?p=admin/actions/commerce/email-preview/render&emailId=1`
Loads `MatrixMate.css`

Here's a [related issue](https://github.com/craftcms/commerce/issues/1950) on Commerce and [the resolution](https://github.com/internetztube/craft-slug-equals-title/issues/12) on the plugin causing it.

**Comment by mmikkel** [comment]
Thanks for reporting that! That's pretty awkward and I was not aware of that issue.

I'd actually consider this a Commerce bug, but I'm going to leave my thoughts on the matter in the Commerce repo issue you linked to.

In any case – yes, MatrixMate could be smarter about not registering its asset bundle for every control panel request, so I'll look into improving that ASAP.

**Comment by mmikkel** [comment]
Should be resolved in [MatrixMate v. 1.4.0](https://github.com/vaersaagod/matrixmate/releases/tag/v1.4.0)!
