### ISSUE TITLE
[Craft4] - Saving entry with error breaks tabs

### ISSUE THREAD

**Issue by leevigraham** [vaersaagod/matrixmate#45]
On a fresh load: 

![image](https://user-images.githubusercontent.com/25124/166403129-d97d62df-d343-48af-bcd1-129f4d19dab9.png)

Saving the entry (Save and Continue) with an error in a matrix block:

![Screen Shot 2022-05-03 at 1 59 28 pm](https://user-images.githubusercontent.com/25124/166403080-9f39fa64-6116-4ad6-be09-d04b1a94ec82.png)

![Screen Shot 2022-05-03 at 1 59 21 pm](https://user-images.githubusercontent.com/25124/166403083-5714946b-304b-4bbb-b2f6-7512a32cb938.png)

**Comment by mmikkel** [comment]
Thanks for reporting that! Just tagged MatrixMate 2.0.0-beta.2, which should fix the issue.
