### ISSUE TITLE
Conflict with SuperTable - triggers "Showing your unsaved changes."

### ISSUE THREAD

**Issue by eve-prefix** [vaersaagod/matrixmate#53]
### Versions
Craft 4.2.0.2
Super Table 3.0.0
MatrixMate 2.1.0

### Issue
When using a Matrix block containing a Super Table field with either an Entry field or a Category field, if the Super Table field is shown in a tab, the "Showing your unsaved changes." message is automatically triggered even if nothing on the page has been changed. This issue does not happen when the Super Table fields are not set in a tab.

**Comment by mmikkel** [comment]
Thanks for reporting that.

Seems there's a problem with MatrixMate block tabs in general on later Craft 4 versions, where changing tabs creates a new autosaved draft (regardless of what fields are in the different tabs or not). Not sure when this started occurring, but it was definitely not an issue on Craft 4.0.

**Comment by mmikkel** [comment]
Closing this in favor of the above issue ☝️
