### ISSUE TITLE
Commerce support

### ISSUE THREAD

**Issue by bpurtoncc** [vaersaagod/matrixmate#55]
Is there any way to have matrixmate settings work for products when using commerce?

**Comment by mmikkel** [comment]
MatrixMate doesn't support Commerce products, and we don't plan to add it ATM. But, I'll label this as a feature request.

In the interim, possibly [Spoon](https://plugins.craftcms.com/spoon?craft4) supports Commerce?

**Comment by Antimated** [comment]
Also looking for commerce support if this would be possbile.

**Comment by eeeeeeeeeve** [comment]
@mmikkel - Added a PR for this, hoping you can take a look! https://github.com/vaersaagod/matrixmate/pull/73

**Comment by daniellelecomte** [comment]
@mmikkel - any chance you've had a moment to review this PR? Would really appreciate it!

**Comment by mmikkel** [comment]
I just tagged MatrixMate v. 2.2.0 with @eeeeeeeeeve's PR [#73](https://github.com/vaersaagod/matrixmate/pull/73) merged, adding support for the `productType:{handle}` config context.
