### ISSUE TITLE
MaxLimit doesn't prevent CMS user from breaking this

### ISSUE THREAD

**Issue by yahm23** [vaersaagod/matrixmate#58]
Setup:
- Craft 4 (4.0.0)
- php 8.1.0
- Matrixmate 2.1.1

We are trying to set a maximum limit of a certain block in a matrix field. The matrix mate config file looks like this:
```
<?php
$thankYouHidden = [
    'table',
    'video',
    'redactor',
    'ctaButton'
];

return [
    'fields' => [
        'contentMain' => [
            '*' =>[
                'hiddenTypes' => [
                    'anchorLink',
                    'communityPanel',
                    'form',
                    'thankYouPanel'
                ]  
            ],
            'entryType:thankYou' => [
                'hiddenTypes' => $thankYouHidden,
                'types' => [
                    'thankYouPanel' => [
                        'maxLimit' => 1,
                    ],
                ],
            ]
        ]
    ],
];
```
The objective is to limit the `thankYouPanel` to a maximum of 1.
This partially works as expected; within our contenMain matrix in the CP we can add a single `thankYouPanel` block. After this, the button is greyed out and 'disabled'. However, the user can still click and add another block. See the attached video for reference. The user can then subsequently save the page with no warnings.

https://user-images.githubusercontent.com/55092073/201081076-d13c8433-f18c-45c9-84a3-77fc993d95f1.mp4

My question is, is this intentional? Is the max limit purely to demonstrate visually only one block is allowed? 

We've used matrixmate before, and this seems to work if there is only a single allowed type of block allowed and the button to add any further blocks completely disappears. ie in the video above, the only solution that seems viable is to remove the other accepted 'Embed' block.

**Comment by mmikkel** [comment]
Thanks for reporting that! Should be fixed in [v. 2.1.2](https://github.com/vaersaagod/matrixmate/releases/tag/v2.1.2).
