### ISSUE TITLE
Rename matrix block type?

### ISSUE THREAD

**Issue by gglnx** [vaersaagod/matrixmate#62]
Would it be possible to add an option to rename a Matrix block type?

**Comment by mmikkel** [comment]
Hi @gglnx, could you describe an example use case? Off the bat I’m not sure if I feel this would be a very useful feature.

**Comment by mmikkel** [comment]
@gglnx Got it. It's actually possible to add a single block type to multiple MatrixMate groups: just add `'logos'` to the `types` array in both the "Inline" and "Section" groups' `types` arrays, and the "Logos" block type should appear in both :)
