### ISSUE TITLE
Craft 5 Migration - Matrix Block Type maxLimit

### ISSUE THREAD

**Issue by npruzaniec** [vaersaagod/matrixmate#76]
Hello, thanks for the great plugin - it has been exactly what we needed! With the end of compatibility with Craft 5, can you give any guidance on natively achieving the `maxLimit` functionality going forward? I have not been able to find a replacement for this functionality yet. Below is our `matrixmate.php` file with how we are using that feature:

```
return [
  'fields' => [
    'block_spacing_options' => [
      'types' => [
        'margin_top' => [
          'maxLimit' => 1,
        ],
        'padding_top' => [
          'maxLimit' => 1,
        ],
        'padding_bottom' => [
          'maxLimit' => 1,
        ],
        'margin_bottom' => [
          'maxLimit' => 1,
        ],
      ]
    ],
    'content_spacing_options' => [
      'types' => [
        'margin_top' => [
          'maxLimit' => 1,
        ],
        'margin_bottom' => [
          'maxLimit' => 1,
        ],
      ]
    ],
  ],
];
```

**Comment by mmikkel** [comment]
As far as I know, there is no equivalent feature in Craft core – you might want to submit a feature request for per-entry type limits [over at the Craft repo](https://github.com/craftcms/cms/discussions/categories/ideas); I haven't seen one.

**Comment by npruzaniec** [comment]
Sounds good, appreciate your quick response!
