### ISSUE TITLE
Breaks when there's a super table field

### ISSUE THREAD

**Issue by JorgeAnzola** [vaersaagod/matrixmate#8]
Apparently, the two plugins are not getting along.

This in the field settings:
<img width="903" alt="Screen Shot 2019-05-29 at 11 40 53" src="https://user-images.githubusercontent.com/15676614/58546962-c6e7b780-8206-11e9-8e87-54f1d28bb8ee.png">

in the input nothing is displayed.

MatrixMate 1.1.4
Super Table 2.1.20
Craft Pro CMS 3.1.28

**Comment by mmikkel** [comment]
Hi @JorgeAnzola – thanks for reporting. What's your setup here – do you have a Matrix field nested inside a SuperTable field, or are the SuperTable and Matrix fields separate fields in the layout?

Can you provide a copy of your `config/matrixmate.php` file (at least the relevant bits)? 

Note that MatrixMate does *not* support Matrix fields nested in SuperTable fields – although stuff should obviously not _break_ like the above error you posted, so there's obviously an issue here :)

**Comment by mmikkel** [comment]
@JorgeAnzola I was able to reproduce an issue where a Matrix field nested in a SuperTable would be hidden, and just pushed a fix for this problem in [MatrixMate 1.1.5](https://github.com/vaersaagod/matrixmate/releases/tag/v1.1.5).
